add_newline = true

command_timeout = 500
format = """
$directory\
$cmd_duration\
$character"""
[line_break]
disabled = true

[character]
success_symbol = "[➜](bold fg:#38d145)"
error_symbol = "[➜](bold fg:#38d145)"

[cmd_duration]
min_time = 500
format = "| took [$duration](bold yellow) "
disabled = false 

[directory]
style = "bold fg:#20A57B"
format = "[$path ]($style)"
truncation_length = 0
#truncation_symbol = "./"

[git_branch]
symbol = "  "
style = "bold #e8ec00 inverted"
format = "on [$symbol$branch ]($style) "

[username]
disabled = true
show_always = true
format = "[$directory]($style)"
style_root = "red bold"

[time]
disabled = true
format = '[$time]($style) '
time_format = "%I:%M:%S %p"
utc_time_offset = "+6"
style = "bold fg:#20A57B"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[package]
disabled = true
